version: 2

sources:
  - name: silver_staging__production
    database: from-warehouse-to-lakehouse
    schema: silver_staging__production
    tables:
      - name: product_list_price_history
        description: "Changes in the list price of a product over time."
        columns:
          - name: product_id
            description: "Product identification number. Foreign key to Product.product_id"
          - name: start_date
            description: "List price start date."
          - name: end_date
            description: "List price end date"
          - name: list_price
            description: "Product list price (Stored as STRING in BQ)."
          - name: modified_date
            description: "Date and time the record was last updated."